fix: restore `warnings.showwarning` value after running pytest (#16)
## Overview

It seems that I'm getting the errors described in
https://github.com/bazel-contrib/rules_python/issues/2762, but only when
using `pytest-bazel`.

```
  File "/private/var/tmp/username/hash/sandbox/darwin-sandbox/code/test.runfiles/pypi_pytest_bazel/site-packages/pytest_bazel/__init__.py", line 39, in main
    sys.exit(_main(args=args))
SystemExit: ExitCode.OK

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/tmp/username/hash/sandbox/darwin-sandbox/code/test.runfiles/mycode/_test_stage2_bootstrap.py", line 547, in <module>
    main()
  File "/private/var/tmp/username/hash/sandbox/darwin-sandbox/code/test.runfiles/mycode/_test_stage2_bootstrap.py", line 541, in main
    with _maybe_collect_coverage(enable=cov_tool is not None):
  File "/private/var/tmp/username/hash/execroot/_main/external/python/lib/python3.10/warnings.py", line 109, in _showwarnmsg
    sw(msg.message, msg.category, msg.filename, msg.lineno,
  File "/private/var/tmp/username/hash/sandbox/darwin-sandbox/9/execroot/_main/bazel-out/mycode/test.runfiles/pypi_pytest_bazel/site-packages/pytest_bazel/main.py", line 42, in _fn
    out_file.write(
ValueError: I/O operation on closed file.
--
Coverage runner: Not collecting coverage for failed test.
The following commands failed with status 1
```

The issue seems to be caused by the overridden `warnings.showwarning`
before running **pytest**. However, after all is done, any other
`warning.warn()` calls still use the `_write_to_file_factory(f)` which
writes to the file dictated by the env var `TEST_WARNINGS_OUTPUT_FILE`.

## Proposed Solution

The previous `warnings.showwarning` value is restored after running
**pytest**.

Any another exception in still propagated through the stack trace as we
don't catch them via the `except` clause. This prevents any other issue
to not be unintentionally hidden.

With this, the errors disappear on my end. 🎉